	TITLE 	Supavet Amornruksakul
	SUBTTL	6210406734
STACK	SEGMENT	STACK
		DW 64 DUP(?)
STACK	ENDS	
DATA	SEGMENT
	POINT	DW	?
	REWARD	DW	?
	SALE	DW	4250
DATA ENDS
CODE	SEGMENT
	ASSUME CS:CODE, DS:DATA, SS:STACK
FIRST	PROC
	MOV	AX,DATA		; initial DS
	MOV	DS,AX
	MOV	AX,SALE		; copy SALE into AX
	MOV	BX,17		; copy 17 into BX
	DIV	BX		; (DX,AX)/BX
	MOV	POINT,AX	; copy AX into POINT
	MOV	CX,2		; copy 2 into CX
	MUL	CX		; CX*AX
	MOV	REWARD,AX	; copy AX into REWARD
	MOV	AH,4CH		; return to DOS
	INT	21H
FIRST	ENDP
CODE	ENDS
	END	FIRST